defmodule WemachatApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :wemachat_api

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_wemachat_api_key",
    signing_salt: "Vo+XB6wh",
    same_site: "Lax"
  ]

  # Chat WebSocket
  socket "/socket", WemachatApiWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :wemachat_api,
    gzip: not code_reloading?,
    only: WemachatApiWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :wemachat_api
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # CORS - Allow requests from Flutter app
  plug CORSPlug, origin: ["http://localhost:4000", "http://10.0.2.2:4000", "*"]

  plug WemachatApiWeb.Router
end
